services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: vereinsverwaltung
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change_this_password

    ports:
      - "1900:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data