spring:
  application:
    name: tuetenverkauf
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never